CREATE TABLE IF NOT EXISTS tb_consultas (
	
	id bigint CONSTRAINT pk_tb_consulta_id PRIMARY KEY generated by default as identity,
	medico_id bigint NOT NULL,
	paciente_id bigint NOT NULL,
	data timestamp NOT NULL,

	CONSTRAINT fk_tb_consulta_medico_id FOREIGN KEY (medico_id) REFERENCES tb_medicos(id),
	CONSTRAINT fk_tb_consulta_paciente_id FOREIGN KEY (paciente_id) REFERENCES tb_pacientes(id)
);